### ISSUE TITLE
Response customization based on request data

### ISSUE THREAD

**Issue by bt** [nutboltu/storybook-addon-mock#44]
Hi there,

Great addon -- I've been using it to mock a couple of views for the design team to work on making pretty before the application is ready to go live.

I have a question though, would it be possible to return different mock data depending on the request? For example, I have a `/data` endpoint but depending on what is passed in the JSON request, it returns a different dataset response.

Thanks!

**Comment by nutboltu** [comment]
@bt  Unfortunately, in the current version, we didn't map the response with the request data. So whatever the request would be it doesn't matter, it cares about the URL path and the status code. 

But you can change the response from the panel. One of the options would be, whatever the request you passed, just change the response from the panel. you will see the result.

**Comment by bt** [comment]
Ah that's unfortunate. It's a bit more complicated for me because my React component makes 4 calls to load data but with 4 different request payloads. Also, there's no button on the component to let me "refresh" the data so the idea of using the panel won't work.

Would this addition be hard to add? I had a quick look at the source and I think I'd know how to do it, but I feel like the panel would also break and I'm not very familiar with Storybook panel/managers.

**Comment by nutboltu** [comment]
@bt Feel free to raise a PR with the feature. I will also spend time onto it. Will give you the update soon

**Comment by DangerStu** [comment]
Any update on this feature ?

**Comment by nutboltu** [comment]
@DangerStu to get more clarity, does the API contain `named parameters` or `query parameters`?

**Comment by DangerStu** [comment]
@nutboltu I just raised a PR for `query parameters`

**Comment by nutboltu** [comment]
This issue is addressed in the new major version [2.0.0](https://github.com/nutboltu/storybook-addon-mock/releases/tag/2.0.0).

We have introduced a response function that contains the request object as a parameter. So you can change the response depending on the request payload.

```js
import React from 'react';
import withMock from 'storybook-addon-mock';
import Component from './Component';

export default {
    title: 'Component',
    component: Component,
    decorators: [withMock],
};

const Template = (args) => <Component {...args} />;

export const Default = Template.bind({});
Default.parameters = {
    mockData: [
        {
            url: 'https://jsonplaceholder.typicode.com/todos?id=1',
            method: 'GET',
            status: 200,
            response: (request) => {
                const {
                    url,
                    method,
                    body,
                    searchParams,
                } = request;

                if (searchParams.id == 1) {
                     return {
                        data: 'Custom data for id 1',
                    };   
                } else if (body.name === 'mock') {
                    return {
                        data: 'Custom data for name mock',
                    }
                }
                return {
                    data: 'Default data',
                }
            },
        },
    ],
};
```

@bt @DangerStu

**Comment by Hypnosphi** [comment]
@nutboltu but it still doesn't support named parameters, right?
